# Azure Deployment Script for Real-Time Transcription App (PowerShell)
# This script helps automate the deployment to Azure Static Web Apps

param(
    [string]$SubscriptionId = "",
    [string]$ResourceGroup = "rg-realtime-transcription",
    [string]$Location = "eastus",
    [string]$AppName = "realtime-transcription-app"
)

$ErrorActionPreference = "Stop"

Write-Host "🚀 Starting Azure deployment for Real-Time Transcription App" -ForegroundColor Green

# Check if Azure CLI is installed
try {
    az --version | Out-Null
    Write-Host "✅ Azure CLI found" -ForegroundColor Green
} catch {
    Write-Host "❌ Azure CLI is not installed. Please install it first." -ForegroundColor Red
    exit 1
}

# Login to Azure
Write-Host "📝 Logging into Azure..." -ForegroundColor Yellow
az login

# Set subscription if provided
if ($SubscriptionId) {
    Write-Host "🎯 Setting subscription to $SubscriptionId" -ForegroundColor Yellow
    az account set --subscription $SubscriptionId
}

# Create resource group
Write-Host "📦 Creating resource group: $ResourceGroup" -ForegroundColor Yellow
az group create --name $ResourceGroup --location $Location

# Create Azure Cognitive Services - Speech
Write-Host "🗣️ Creating Speech Service..." -ForegroundColor Yellow
$SpeechName = "speech-$AppName"
az cognitiveservices account create `
    --name $SpeechName `
    --resource-group $ResourceGroup `
    --kind SpeechServices `
    --sku S0 `
    --location $Location `
    --yes

# Create Azure Cognitive Services - Translator
Write-Host "🌐 Creating Translator Service..." -ForegroundColor Yellow
$TranslatorName = "translator-$AppName"
az cognitiveservices account create `
    --name $TranslatorName `
    --resource-group $ResourceGroup `
    --kind TextTranslation `
    --sku S1 `
    --location global `
    --yes

# Get Speech Service key
Write-Host "🔑 Retrieving Speech Service key..." -ForegroundColor Yellow
$SpeechKey = az cognitiveservices account keys list `
    --name $SpeechName `
    --resource-group $ResourceGroup `
    --query "key1" `
    --output tsv

# Get Translator Service key
Write-Host "🔑 Retrieving Translator Service key..." -ForegroundColor Yellow
$TranslatorKey = az cognitiveservices account keys list `
    --name $TranslatorName `
    --resource-group $ResourceGroup `
    --query "key1" `
    --output tsv

# Display configuration
Write-Host "✅ Deployment setup complete!" -ForegroundColor Green
Write-Host "📋 Configuration Summary:" -ForegroundColor Green
Write-Host "Resource Group: $ResourceGroup"
Write-Host "Location: $Location"
Write-Host "Speech Service: $SpeechName"
Write-Host "Translator Service: $TranslatorName"
Write-Host "🔐 Important: Save these keys securely!" -ForegroundColor Red
Write-Host "Speech Key: $SpeechKey"
Write-Host "Translator Key: $TranslatorKey"
Write-Host "Region: $Location"

# Create environment file
Write-Host "📝 Creating .env.local file..." -ForegroundColor Yellow
@"
# Azure Configuration - Generated by deployment script
AZURE_SUBSCRIPTION_KEY=$SpeechKey
AZURE_REGION=$Location
NODE_ENV=production
DEFAULT_LANGUAGE=en-US
DEFAULT_TARGET_LANGUAGE=es
"@ | Out-File -FilePath ".env.local" -Encoding UTF8

Write-Host "✅ Created .env.local with your Azure credentials" -ForegroundColor Green
Write-Host "⚠️ Remember to add these as secrets in your GitHub repository:" -ForegroundColor Yellow
Write-Host "   - AZURE_SUBSCRIPTION_KEY: $SpeechKey"
Write-Host "   - AZURE_REGION: $Location"

# Static Web App creation note
Write-Host "⚠️ Static Web App creation requires GitHub integration." -ForegroundColor Yellow
Write-Host "   Please complete the following steps in Azure Portal:" -ForegroundColor Yellow
Write-Host "   1. Go to portal.azure.com" -ForegroundColor Yellow
Write-Host "   2. Create a Static Web App resource" -ForegroundColor Yellow
Write-Host "   3. Connect to your GitHub repository" -ForegroundColor Yellow
Write-Host "   4. Use the following settings:" -ForegroundColor Yellow
Write-Host "      - Resource Group: $ResourceGroup" -ForegroundColor Yellow
Write-Host "      - Name: swa-$AppName" -ForegroundColor Yellow
Write-Host "      - App location: /" -ForegroundColor Yellow
Write-Host "      - Output location: (leave empty)" -ForegroundColor Yellow

Write-Host "🎉 Deployment setup complete!" -ForegroundColor Green
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Complete Static Web App setup in Azure Portal"
Write-Host "2. Push your code to GitHub"
Write-Host "3. Configure GitHub secrets for CI/CD"
Write-Host "4. Test your deployed application"

# Pause to allow user to read the output
Read-Host "Press Enter to continue..."
