#!/bin/bash

# Azure Deployment Script for Real-Time Transcription App
# This script helps automate the deployment to Azure Static Web Apps

set -e

# Configuration
RESOURCE_GROUP="rg-realtime-transcription"
LOCATION="eastus"
APP_NAME="realtime-transcription-app"
SUBSCRIPTION_ID=""  # Add your subscription ID here

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}🚀 Starting Azure deployment for Real-Time Transcription App${NC}"

# Check if Azure CLI is installed
if ! command -v az &> /dev/null; then
    echo -e "${RED}❌ Azure CLI is not installed. Please install it first.${NC}"
    exit 1
fi

# Login to Azure
echo -e "${YELLOW}📝 Logging into Azure...${NC}"
az login

# Set subscription if provided
if [ ! -z "$SUBSCRIPTION_ID" ]; then
    echo -e "${YELLOW}🎯 Setting subscription to $SUBSCRIPTION_ID${NC}"
    az account set --subscription $SUBSCRIPTION_ID
fi

# Create resource group
echo -e "${YELLOW}📦 Creating resource group: $RESOURCE_GROUP${NC}"
az group create --name $RESOURCE_GROUP --location $LOCATION

# Create Azure Cognitive Services - Speech
echo -e "${YELLOW}🗣️  Creating Speech Service...${NC}"
SPEECH_NAME="speech-$APP_NAME"
az cognitiveservices account create \
    --name $SPEECH_NAME \
    --resource-group $RESOURCE_GROUP \
    --kind SpeechServices \
    --sku S0 \
    --location $LOCATION \
    --yes

# Create Azure Cognitive Services - Translator
echo -e "${YELLOW}🌐 Creating Translator Service...${NC}"
TRANSLATOR_NAME="translator-$APP_NAME"
az cognitiveservices account create \
    --name $TRANSLATOR_NAME \
    --resource-group $RESOURCE_GROUP \
    --kind TextTranslation \
    --sku S1 \
    --location global \
    --yes

# Get Speech Service key
echo -e "${YELLOW}🔑 Retrieving Speech Service key...${NC}"
SPEECH_KEY=$(az cognitiveservices account keys list \
    --name $SPEECH_NAME \
    --resource-group $RESOURCE_GROUP \
    --query "key1" \
    --output tsv)

# Get Translator Service key
echo -e "${YELLOW}🔑 Retrieving Translator Service key...${NC}"
TRANSLATOR_KEY=$(az cognitiveservices account keys list \
    --name $TRANSLATOR_NAME \
    --resource-group $RESOURCE_GROUP \
    --query "key1" \
    --output tsv)

# Create Static Web App
echo -e "${YELLOW}🌐 Creating Static Web App...${NC}"
STATIC_APP_NAME="swa-$APP_NAME"

# Note: Static Web App creation requires GitHub integration
# This will need to be completed in the Azure Portal
echo -e "${YELLOW}⚠️  Static Web App creation requires GitHub integration.${NC}"
echo -e "${YELLOW}   Please complete the following steps in Azure Portal:${NC}"
echo -e "${YELLOW}   1. Go to portal.azure.com${NC}"
echo -e "${YELLOW}   2. Create a Static Web App resource${NC}"
echo -e "${YELLOW}   3. Connect to your GitHub repository${NC}"
echo -e "${YELLOW}   4. Use the following settings:${NC}"
echo -e "${YELLOW}      - Resource Group: $RESOURCE_GROUP${NC}"
echo -e "${YELLOW}      - Name: $STATIC_APP_NAME${NC}"
echo -e "${YELLOW}      - App location: /${NC}"
echo -e "${YELLOW}      - Output location: (leave empty)${NC}"

# Display configuration
echo -e "${GREEN}✅ Deployment setup complete!${NC}"
echo -e "${GREEN}📋 Configuration Summary:${NC}"
echo -e "Resource Group: $RESOURCE_GROUP"
echo -e "Location: $LOCATION"
echo -e "Speech Service: $SPEECH_NAME"
echo -e "Translator Service: $TRANSLATOR_NAME"
echo -e "${RED}🔐 Important: Save these keys securely!${NC}"
echo -e "Speech Key: $SPEECH_KEY"
echo -e "Translator Key: $TRANSLATOR_KEY"
echo -e "Region: $LOCATION"

# Create environment file
echo -e "${YELLOW}📝 Creating .env.local file...${NC}"
cat > .env.local << EOF
# Azure Configuration - Generated by deployment script
AZURE_SUBSCRIPTION_KEY=$SPEECH_KEY
AZURE_REGION=$LOCATION
NODE_ENV=production
DEFAULT_LANGUAGE=en-US
DEFAULT_TARGET_LANGUAGE=es
EOF

echo -e "${GREEN}✅ Created .env.local with your Azure credentials${NC}"
echo -e "${YELLOW}⚠️  Remember to add these as secrets in your GitHub repository:${NC}"
echo -e "   - AZURE_SUBSCRIPTION_KEY: $SPEECH_KEY"
echo -e "   - AZURE_REGION: $LOCATION"

# Update config.js with production values
echo -e "${YELLOW}📝 Updating config.js for production...${NC}"
cp config.js config.js.backup
sed -i "s/Your Azure Speech Service subscription key/$SPEECH_KEY/g" config.js

echo -e "${GREEN}🎉 Deployment setup complete!${NC}"
echo -e "${YELLOW}Next steps:${NC}"
echo -e "1. Complete Static Web App setup in Azure Portal"
echo -e "2. Push your code to GitHub"
echo -e "3. Configure GitHub secrets for CI/CD"
echo -e "4. Test your deployed application"
